# Generated by Django 6.1.2 on 2026-10-07 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaRifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lista', models.IntegerField(unique=True, verbose_name='N° de Lista / Talonario')),
            ],
        ),
        migrations.CreateModel(
            name='NumeroRifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número (1 al 10)')),
                ('nombre_comprador', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Comprador')),
                ('celular_comprador', models.CharField(blank=True, max_length=20, null=True, verbose_name='N° Celular')),
                ('pagado', models.BooleanField(default=False, verbose_name='¿Pagado?')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros', to='gestion_rifa.listarifa', verbose_name='Lista')),
            ],
        ),
    ]
