# Generated by Django 6.1.2 on 2026-10-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rifa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numerorifa',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Pago'),
        ),
        migrations.AlterField(
            model_name='listarifa',
            name='numero_lista',
            field=models.IntegerField(unique=True, verbose_name='N° de Lista'),
        ),
        migrations.AlterField(
            model_name='numerorifa',
            name='celular_comprador',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='numerorifa',
            name='nombre_comprador',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre'),
        ),
    ]
