# Generated by Django 6.1.2 on 2026-10-07 22:43
from django.db import migrations

def crear_listas_y_numeros(apps, schema_editor):
    ListaRifa = apps.get_model('gestion_rifa', 'ListaRifa')
    NumeroRifa = apps.get_model('gestion_rifa', 'NumeroRifa')
    
    # Creamos 60 listas
    for i in range(1, 61):
        lista, creada = ListaRifa.objects.get_or_create(numero_lista=i)
        # Para cada lista, creamos 10 números
        for num in range(1, 11):
            NumeroRifa.objects.get_or_create(
                lista=lista,
                numero=num,
                defaults={'pagado': False}
            )

class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rifa', '0001_initial'),  # Que apunte a la última migración anterior
    ]

    operations = [
        migrations.RunPython(crear_listas_y_numeros),
    ]
