# Generated by Django 6.1.2 on 2026-10-07 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rifa', '0002_numerorifa_fecha_pago_alter_listarifa_numero_lista_and_more'),
        ('gestion_rifa', '0003_poblar_listas_rifa'),
    ]

    operations = [
    ]
