# Generated by Django 6.1.2 on 2026-10-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rifa', '0004_merge_20261007_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='numerorifa',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=20, null=True),
        ),
    ]
